// Official NWS alert colors (from https://www.weather.gov/help-map).
// Keyed by lowercase event name. Returns hex.
const COLORS: Record<string, string> = {
  "tsunami warning": "#FD6347",
  "tornado warning": "#FF0000",
  "extreme wind warning": "#FF8C00",
  "severe thunderstorm warning": "#FFA500",
  "flash flood warning": "#8B0000",
  "flash flood statement": "#8B0000",
  "severe weather statement": "#00FFFF",
  "shelter in place warning": "#FA8072",
  "evacuation immediate": "#7FFF00",
  "civil danger warning": "#FFB6C1",
  "nuclear power plant warning": "#4B0082",
  "radiological hazard warning": "#4B0082",
  "hazardous materials warning": "#4B0082",
  "fire warning": "#A0522D",
  "civil emergency message": "#FFB6C1",
  "law enforcement warning": "#C0C0C0",
  "storm surge warning": "#B524F7",
  "hurricane force wind warning": "#CD5C5C",
  "hurricane warning": "#DC143C",
  "typhoon warning": "#DC143C",
  "special marine warning": "#FFA500",
  "blizzard warning": "#FF4500",
  "snow squall warning": "#C71585",
  "ice storm warning": "#8B008B",
  "heavy snow warning": "#138CFA",
  "winter storm warning": "#FF69B4",
  "high wind warning": "#DAA520",
  "tropical storm warning": "#B22222",
  "storm warning": "#9400D3",
  "tropical depression warning": "#9400D3",
  "tsunami advisory": "#D2691E",
  "tsunami watch": "#FF00FF",
  "avalanche warning": "#1E90FF",
  "earthquake warning": "#8B4513",
  "volcano warning": "#2F4F4F",
  "ashfall warning": "#A9A9A9",
  "coastal flood warning": "#228B22",
  "lakeshore flood warning": "#228B22",
  "flood warning": "#00FF00",
  "high surf warning": "#228B22",
  "dust storm warning": "#FFE4C4",
  "blowing dust warning": "#FFE4C4",
  "lake effect snow warning": "#008B8B",
  "excessive heat warning": "#C71585",
  "extreme heat warning": "#C71585",
  "tornado watch": "#FFFF00",
  "severe thunderstorm watch": "#DB7093",
  "flash flood watch": "#2E8B57",
  "gale warning": "#DDA0DD",
  "flood statement": "#00FF00",
  "extreme cold warning": "#0000FF",
  "wind chill warning": "#B0C4DE",
  "lake effect snow advisory": "#48D1CC",
  "winter weather advisory": "#7B68EE",
  "wind advisory": "#D2B48C",
  "lake wind advisory": "#D2B48C",
  "blowing dust advisory": "#BDB76B",
  "hard freeze warning": "#9400D3",
  "freeze warning": "#483D8B",
  "red flag warning": "#FF1493",
  "storm watch": "#FFE4B5",
  "hurricane watch": "#FF00FF",
  "hurricane force wind watch": "#9932CC",
  "typhoon watch": "#FF00FF",
  "tropical storm watch": "#F08080",
  "storm surge watch": "#DB7FF7",
  "hurricane local statement": "#FFE4B5",
  "winter storm watch": "#4682B4",
  "avalanche advisory": "#CD853F",
  "avalanche watch": "#F4A460",
  "blizzard watch": "#ADFF2F",
  "rip current statement": "#40E0D0",
  "beach hazards statement": "#40E0D0",
  "gale watch": "#FFC0CB",
  "extreme heat watch": "#800000",
  "excessive heat watch": "#800000",
  "extreme cold watch": "#5F9EA0",
  "wind chill watch": "#5F9EA0",
  "lake effect snow watch": "#87CEFA",
  "hard freeze watch": "#4169E1",
  "freeze watch": "#00FFFF",
  "fire weather watch": "#FFDEAD",
  "extreme fire danger": "#E9967A",
  "911 telephone outage": "#C0C0C0",
  "coastal flood watch": "#66CDAA",
  "lakeshore flood watch": "#66CDAA",
  "flash flood emergency": "#8B0000",
  "tornado emergency": "#FF0000",
  "flood watch": "#2E8B57",
  "high wind watch": "#B8860B",
  "extreme wind watch": "#FF8C00",
  "small craft advisory": "#D8BFD8",
  "small craft advisory for winds": "#D8BFD8",
  "small craft advisory for rough bar": "#D8BFD8",
  "small craft advisory for hazardous seas": "#D8BFD8",
  "brisk wind advisory": "#D8BFD8",
  "hazardous seas warning": "#D8BFD8",
  "hazardous seas watch": "#483D8B",
  "dense fog advisory": "#708090",
  "dense smoke advisory": "#F0E68C",
  "small stream flood advisory": "#00FF7F",
  "arroyo and small stream flood advisory": "#00FF7F",
  "urban and small stream flood advisory": "#00FF7F",
  "flood advisory": "#00FF7F",
  "hydrologic advisory": "#00FF7F",
  "lakeshore flood advisory": "#7CFC00",
  "coastal flood advisory": "#7CFC00",
  "lakeshore flood statement": "#6B8E23",
  "coastal flood statement": "#6B8E23",
  "ashfall advisory": "#696969",
  "freezing fog advisory": "#008080",
  "freezing spray advisory": "#00BFFF",
  "heavy freezing spray warning": "#00BFFF",
  "low water advisory": "#A52A2A",
  "frost advisory": "#6495ED",
  "heat advisory": "#FF7F50",
  "cold weather advisory": "#AFEEEE",
  "wind chill advisory": "#AFEEEE",
  "urban and small stream flood statement": "#00FF7F",
  "flood statement (hydro)": "#00FF7F",
  "hydrologic outlook": "#90EE90",
  "hazardous weather outlook": "#EEE8AA",
  "short term forecast": "#98FB98",
  "special weather statement": "#FFE4B5",
  "marine weather statement": "#FFDAB9",
  "great lakes marine weather message": "#FFDAB9",
  "administrative message": "#C0C0C0",
  "test message": "#F0FFFF",
  "required monthly test": "#F0FFFF",
  "required weekly test": "#F0FFFF",
  "practice / demo warning": "#F0FFFF",
  "child abduction emergency": "#FFFFFF",
  "local area emergency": "#C0C0C0",
  "air quality alert": "#808080",
  "air stagnation advisory": "#808080",
  "space weather warning": "#9370DB",
  "space weather watch": "#9370DB",
  "space weather advisory": "#9370DB",
  "river flood warning": "#00FF00",
  "river flood watch": "#2E8B57",
  "river flood statement": "#00FF00",
  "areal flood warning": "#00FF00",
  "areal flood watch": "#2E8B57",
  "areal flood advisory": "#00FF7F",
  "dam break warning": "#8B0000",
};

export function colorForEvent(event: string | undefined | null): string {
  if (!event) return "#808080";
  const key = event.trim().toLowerCase();
  if (COLORS[key]) return COLORS[key];
  // Fallback by suffix
  if (key.includes("warning")) return "#FF8C00";
  if (key.includes("watch")) return "#FFFF00";
  if (key.includes("advisory")) return "#D2B48C";
  if (key.includes("statement")) return "#00FFFF";
  return "#808080";
}

// Returns whether the color is light (needs dark text).
export function isLightColor(hex: string): boolean {
  const h = hex.replace("#", "");
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  const lum = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return lum > 0.6;
}
