/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebcamsRouteImport } from './routes/webcams'
import { Route as TropicalRouteImport } from './routes/tropical'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as StormReportsRouteImport } from './routes/storm-reports'
import { Route as SatelliteRouteImport } from './routes/satellite'
import { Route as OutlookRouteImport } from './routes/outlook'
import { Route as MesoscaleRouteImport } from './routes/mesoscale'
import { Route as LightningRouteImport } from './routes/lightning'
import { Route as ForecastsRouteImport } from './routes/forecasts'
import { Route as CommandRouteImport } from './routes/command'
import { Route as ClimateRouteImport } from './routes/climate'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertsMapRouteImport } from './routes/alerts-map'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'

const WebcamsRoute = WebcamsRouteImport.update({
  id: '/webcams',
  path: '/webcams',
  getParentRoute: () => rootRouteImport,
} as any)
const TropicalRoute = TropicalRouteImport.update({
  id: '/tropical',
  path: '/tropical',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const StormReportsRoute = StormReportsRouteImport.update({
  id: '/storm-reports',
  path: '/storm-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SatelliteRoute = SatelliteRouteImport.update({
  id: '/satellite',
  path: '/satellite',
  getParentRoute: () => rootRouteImport,
} as any)
const OutlookRoute = OutlookRouteImport.update({
  id: '/outlook',
  path: '/outlook',
  getParentRoute: () => rootRouteImport,
} as any)
const MesoscaleRoute = MesoscaleRouteImport.update({
  id: '/mesoscale',
  path: '/mesoscale',
  getParentRoute: () => rootRouteImport,
} as any)
const LightningRoute = LightningRouteImport.update({
  id: '/lightning',
  path: '/lightning',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastsRoute = ForecastsRouteImport.update({
  id: '/forecasts',
  path: '/forecasts',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ClimateRoute = ClimateRouteImport.update({
  id: '/climate',
  path: '/climate',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsMapRoute = AlertsMapRouteImport.update({
  id: '/alerts-map',
  path: '/alerts-map',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts-map': typeof AlertsMapRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/climate': typeof ClimateRoute
  '/command': typeof CommandRoute
  '/forecasts': typeof ForecastsRoute
  '/lightning': typeof LightningRoute
  '/mesoscale': typeof MesoscaleRoute
  '/outlook': typeof OutlookRoute
  '/satellite': typeof SatelliteRoute
  '/storm-reports': typeof StormReportsRoute
  '/tools': typeof ToolsRoute
  '/tropical': typeof TropicalRoute
  '/webcams': typeof WebcamsRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts-map': typeof AlertsMapRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/climate': typeof ClimateRoute
  '/command': typeof CommandRoute
  '/forecasts': typeof ForecastsRoute
  '/lightning': typeof LightningRoute
  '/mesoscale': typeof MesoscaleRoute
  '/outlook': typeof OutlookRoute
  '/satellite': typeof SatelliteRoute
  '/storm-reports': typeof StormReportsRoute
  '/tools': typeof ToolsRoute
  '/tropical': typeof TropicalRoute
  '/webcams': typeof WebcamsRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alerts-map': typeof AlertsMapRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/climate': typeof ClimateRoute
  '/command': typeof CommandRoute
  '/forecasts': typeof ForecastsRoute
  '/lightning': typeof LightningRoute
  '/mesoscale': typeof MesoscaleRoute
  '/outlook': typeof OutlookRoute
  '/satellite': typeof SatelliteRoute
  '/storm-reports': typeof StormReportsRoute
  '/tools': typeof ToolsRoute
  '/tropical': typeof TropicalRoute
  '/webcams': typeof WebcamsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts-map'
    | '/auth'
    | '/changelog'
    | '/climate'
    | '/command'
    | '/forecasts'
    | '/lightning'
    | '/mesoscale'
    | '/outlook'
    | '/satellite'
    | '/storm-reports'
    | '/tools'
    | '/tropical'
    | '/webcams'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts-map'
    | '/auth'
    | '/changelog'
    | '/climate'
    | '/command'
    | '/forecasts'
    | '/lightning'
    | '/mesoscale'
    | '/outlook'
    | '/satellite'
    | '/storm-reports'
    | '/tools'
    | '/tropical'
    | '/webcams'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alerts-map'
    | '/auth'
    | '/changelog'
    | '/climate'
    | '/command'
    | '/forecasts'
    | '/lightning'
    | '/mesoscale'
    | '/outlook'
    | '/satellite'
    | '/storm-reports'
    | '/tools'
    | '/tropical'
    | '/webcams'
    | '/_authenticated/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlertsMapRoute: typeof AlertsMapRoute
  AuthRoute: typeof AuthRoute
  ChangelogRoute: typeof ChangelogRoute
  ClimateRoute: typeof ClimateRoute
  CommandRoute: typeof CommandRoute
  ForecastsRoute: typeof ForecastsRoute
  LightningRoute: typeof LightningRoute
  MesoscaleRoute: typeof MesoscaleRoute
  OutlookRoute: typeof OutlookRoute
  SatelliteRoute: typeof SatelliteRoute
  StormReportsRoute: typeof StormReportsRoute
  ToolsRoute: typeof ToolsRoute
  TropicalRoute: typeof TropicalRoute
  WebcamsRoute: typeof WebcamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webcams': {
      id: '/webcams'
      path: '/webcams'
      fullPath: '/webcams'
      preLoaderRoute: typeof WebcamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tropical': {
      id: '/tropical'
      path: '/tropical'
      fullPath: '/tropical'
      preLoaderRoute: typeof TropicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storm-reports': {
      id: '/storm-reports'
      path: '/storm-reports'
      fullPath: '/storm-reports'
      preLoaderRoute: typeof StormReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellite': {
      id: '/satellite'
      path: '/satellite'
      fullPath: '/satellite'
      preLoaderRoute: typeof SatelliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlook': {
      id: '/outlook'
      path: '/outlook'
      fullPath: '/outlook'
      preLoaderRoute: typeof OutlookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesoscale': {
      id: '/mesoscale'
      path: '/mesoscale'
      fullPath: '/mesoscale'
      preLoaderRoute: typeof MesoscaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lightning': {
      id: '/lightning'
      path: '/lightning'
      fullPath: '/lightning'
      preLoaderRoute: typeof LightningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasts': {
      id: '/forecasts'
      path: '/forecasts'
      fullPath: '/forecasts'
      preLoaderRoute: typeof ForecastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/climate': {
      id: '/climate'
      path: '/climate'
      fullPath: '/climate'
      preLoaderRoute: typeof ClimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts-map': {
      id: '/alerts-map'
      path: '/alerts-map'
      fullPath: '/alerts-map'
      preLoaderRoute: typeof AlertsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlertsMapRoute: AlertsMapRoute,
  AuthRoute: AuthRoute,
  ChangelogRoute: ChangelogRoute,
  ClimateRoute: ClimateRoute,
  CommandRoute: CommandRoute,
  ForecastsRoute: ForecastsRoute,
  LightningRoute: LightningRoute,
  MesoscaleRoute: MesoscaleRoute,
  OutlookRoute: OutlookRoute,
  SatelliteRoute: SatelliteRoute,
  StormReportsRoute: StormReportsRoute,
  ToolsRoute: ToolsRoute,
  TropicalRoute: TropicalRoute,
  WebcamsRoute: WebcamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
